[package]
name = "myStrangeAddiction"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.26.1"
crypto-bigint = "0.5.2"
num = {version = "0.4.0", features = ["rand"]}
rand = "0.8.5" 
tui = "0.19.0"

